export const ADD_REMINDER = "ADD_REMINDER";
export const DELETE_REMINDER = "DELETE_REMINDER";


export const ADD_CLASS_REMINDER = "ADD_CLASS_REMINDER";
export const DELETE_CURRENT_REMINDER = "DELETE_CURRENT_REMINDER";
export const ADD_STUDENT_REMINDER = "ADD_STUDENT_REMINDER";
export const CLEAR_STUDENT_REMINDER = "CLEAR_STUDENT_REMINDER";
export const EDIT_STUDENT_REMINDER = "EDIT_STUDENT_REMINDER";
export const SET_CURRENT_DESK = "SET_CURRENT_DESK";
export const INCREMENT_CURRENT_REMINDER = "INCREMENT_CURRENT_REMINDER";
export const INCREMENT_CURRENT_PROGRESS_SCALE = "INCREMENT_CURRENT_PROGRESS_SCALE";
export const DECREMENT_CURRENT_REMINDER = "DECREMENT_CURRENT_REMINDER";
export const DECREMENT_CURRENT_PROGRESS_SCALE = "DECREMENT_CURRENT_PROGRESS_SCALE";
export const SWAP_STUDENTS = "SWAP_STUDENTS";
export const INCREMENT_STUDENT_PROGRESS = "INCREMENT_STUDENT_PROGRESS";
export const DECREMENT_STUDENT_PROGRESS = "DECREMENT_STUDENT_PROGRESS";
export const SET_STUDENT_FLAG = "SET_STUDENT_FLAG";
export const EDIT_CURRENT_PROGRESS_SCALE = "EDIT_CURRENT_PROGRESS_SCALE";
export const CLASSROOM_ERROR = "CLASSROOM_ERROR";
