export const ADD_CLASS_REMINDER = "ADD_CLASS_REMINDER";
export const DELETE_CURRENT_REMINDER = "DELETE_CURRENT_REMINDER";
export const CLEAR_STUDENT_REMINDER = "CLEAR_STUDENT_REMINDER";
export const EDIT_STUDENT_REMINDER = "EDIT_STUDENT_REMINDER";
export const SET_CURRENT_DESK = "SET_CURRENT_DESK";
export const INCREMENT_CURRENT_REMINDER = "INCREMENT_CURRENT_REMINDER";
export const INCREMENT_CURRENT_PROGRESS_SCALE =
  "INCREMENT_CURRENT_PROGRESS_SCALE";
export const DECREMENT_CURRENT_REMINDER = "DECREMENT_CURRENT_REMINDER";
export const DECREMENT_CURRENT_PROGRESS_SCALE =
  "DECREMENT_CURRENT_PROGRESS_SCALE";
export const INCREMENT_STUDENT_PROGRESS = "INCREMENT_STUDENT_PROGRESS";
export const DECREMENT_STUDENT_PROGRESS = "DECREMENT_STUDENT_PROGRESS";
export const CYCLE_STUDENT_FLAG = "SET_STUDENT_FLAG";
export const STUDENT_FLAG_COUNT = 4;
export const SWAP_STUDENTS = "SWAP_STUDENTS";
export const EDIT_CURRENT_PROGRESS_SCALE = "EDIT_CURRENT_PROGRESS_SCALE";
export const TOGGLE_SHOW_REMINDERS = "TOGGLE_SHOW_REMINDERS";
export const FLIP_CLASSROOM = "FLIP_CLASSROOM";
export const TOGGLE_SWAPPING = "TOGGLE_SWAPPING";

export const CLEAR_CURRENT_CLASS = "CLEAR_CURRENT_CLASS";
