// CLASSROOM CONTEXT OPERATIONS
export const ADD_CLASS_REMINDER = "ADD_CLASS_REMINDER";
export const DELETE_CURRENT_REMINDER = "DELETE_CURRENT_REMINDER";
export const CLEAR_STUDENT_REMINDER = "CLEAR_STUDENT_REMINDER";
export const EDIT_STUDENT_REMINDER = "EDIT_STUDENT_REMINDER";
export const SET_CURRENT_DESK = "SET_CURRENT_DESK";
export const INCREMENT_CURRENT_REMINDER = "INCREMENT_CURRENT_REMINDER";
export const INCREMENT_CURRENT_PROGRESS_SCALE =
  "INCREMENT_CURRENT_PROGRESS_SCALE";
export const DECREMENT_CURRENT_REMINDER = "DECREMENT_CURRENT_REMINDER";
export const DECREMENT_CURRENT_PROGRESS_SCALE =
  "DECREMENT_CURRENT_PROGRESS_SCALE";
export const INCREMENT_STUDENT_PROGRESS = "INCREMENT_STUDENT_PROGRESS";
export const DECREMENT_STUDENT_PROGRESS = "DECREMENT_STUDENT_PROGRESS";
export const CYCLE_STUDENT_FLAG = "SET_STUDENT_FLAG";
export const STUDENT_FLAG_COUNT = 4;
export const SWAP_STUDENTS = "SWAP_STUDENTS";
export const EDIT_CURRENT_PROGRESS_SCALE = "EDIT_CURRENT_PROGRESS_SCALE";
export const TOGGLE_SHOW_REMINDERS = "TOGGLE_SHOW_REMINDERS";
export const FLIP_CLASSROOM = "FLIP_CLASSROOM";
export const TOGGLE_SWAPPING = "TOGGLE_SWAPPING";
export const INITIALIZE_CLASSROOM_CONTEXT = "INITIALIZE_CLASSROOM_CONTEXT";
export const SET_CURRENT_SET_IN_ROOM = "SET_CURRENT_SET_IN_ROOM";

// GLOBAL CONTEXT OPERATIONS
export const CLEAR_CURRENT_SET = "CLEAR_CURRENT_SET";
export const CLEAR_CURRENT_ROOM = "CLEAR_CURRENT_ROOM";
export const SET_CURRENT_SET = "SET_CURRENT_SET";
export const SET_CURRENT_ROOM = "SET_CURRENT_ROOM";
export const ADD_SET = "ADD_SET";
export const ADD_ROOM = "ADD_ROOM";
export const EDIT_CURRENT_SET = "EDIT_CURRENT_SET";
export const EDIT_CURRENT_ROOM = "EDIT_CURRENT_ROOM";
export const EDIT_CURRENT_SEATING = "EDIT_CURRENT_SEATING";
export const DELETE_CURRENT_SET = "DELETE_CURRENT_SET";
export const DELETE_CURRENT_ROOM = "DELETE_CURRENT_ROOM";
export const UPDATE_LOCAL_STORAGE = "UPDATE_LOCAL STORAGE";
